name: publish to nuget
on:
  push:
    branches:
      - master

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build project
        run: dotnet build -c Release

      - name: Build project package
        run: dotnet pack --no-build -c Release -o .
                
      - name: Publish to nuget packages 
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
